# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.FileField(blank=True, null=True, upload_to=' ')),
                ('date_uploaded', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('render_type', models.CharField(blank=True, choices=[('Scatter', 'Scatter'), ('Bar', 'Bar'), ('Histogram', 'Histogram')], max_length=255, null=True)),
                ('date_uploaded', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
