# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pychart_profile', '0001_initial'),
        ('pychart_datarender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='owner',
        ),
        migrations.AddField(
            model_name='data',
            name='owner',
            field=models.ManyToManyField(null=True, related_name='data_sets', to='pychart_profile.PyChartProfile'),
        ),
    ]
