# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pychart_datarender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='render',
            name='render',
            field=models.FileField(blank=True, null=True, upload_to='render'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='data'),
        ),
    ]
