# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pychart_datarender', '0002_auto_20170216_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='owner',
            field=models.ManyToManyField(blank=True, null=True, related_name='data_sets', to='pychart_profile.PyChartProfile'),
        ),
    ]
