# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pychart_datarender', '0002_auto_20170213_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='render',
            name='render',
            field=models.TextField(blank=True, null=True),
        ),
    ]
