# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pychart_datarender', '0004_auto_20170213_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='render',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='pychart_profile.PyChartProfile'),
        ),
    ]
